# Generated by Django 5.0.1 on 2024-06-21 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_orderitem_final_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$')]),
        ),
    ]
